name: llm-merging
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - python=3.10.14=h955ad1f_0
  - pytorch=2.2.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.2.0=py310
  - typing_extensions=4.9.0=py310h06a4308_1
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.29.1
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - altair==5.3.0
    - annotated-types==0.6.0
    - anyio==4.3.0
    - appdirs==1.4.4
    - astor==0.8.1
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - base58==2.1.1
    - black==21.12b0
    - blinker==1.7.0
    - brotli==1.1.0
    - cachetools==5.3.3
    - certifi==2024.2.2
    - click==7.1.2
    - datasets==2.18.0
    - decorator==5.1.1
    - dill==0.3.8
    - distro==1.9.0
    - evaluate==0.4.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - filelock==3.13.1
    - fire==0.6.0
    - flake8==7.0.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - git+https://github.com/bigscience-workshop/promptsource
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gmpy2==2.1.2
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.22.2
    - idna==3.4
    - inflate64==1.0.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - ipython==8.23.0
    - isort==5.8.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.4.0
    - jsonschema-specifications==2023.12.1
    - jsonschema==4.21.1
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.0.5
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - multivolumefile==0.2.3
    - mypy-extensions==1.0.0
    - networkx==3.1
    - nltk==3.8.1
    - numpy==1.26.4
    - openai==1.17.1
    - packaging==24.0
    - pandas==2.2.1
    - parso==0.8.4
    - pathspec==0.12.1
    - peft==0.10.0
    - pexpect==4.9.0
    - pillow==10.2.0
    - pip==24.0
    - plotly==5.20.0
    - pluggy==1.4.0
    - prompt-toolkit==3.0.43
    - protobuf==5.26.1
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py7zr==0.21.0
    - pyarrow-hotfix==0.6
    - pyarrow==15.0.2
    - pybcj==1.0.2
    - pycodestyle==2.11.1
    - pycryptodomex==3.20.0
    - pydantic-core==2.18.1
    - pydantic==2.7.0
    - pydeck==0.8.1b0
    - pyflakes==3.2.0
    - pygments==2.17.2
    - pyppmd==1.1.0
    - pytest==8.1.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzstd==0.15.10
    - referencing==0.34.0
    - regex==2023.12.25
    - requests==2.31.0
    - responses==0.18.0
    - rouge_score==0.1.2
    - rpds-py==0.18.0
    - safetensors==0.4.2
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - setuptools==68.2.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - stack-data==0.6.3
    - streamlit==0.82.0
    - sympy==1.12
    - tempdir==0.7.1
    - tenacity==8.2.3
    - termcolor==2.4.0
    - texttable==1.7.0
    - threadpoolctl==3.4.0
    - tokenizers==0.15.2
    - toml==0.10.2
    - tomli==1.2.3
    - toolz==0.12.1
    - torch==2.2.2
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - tornado==6.4
    - tqdm==4.66.2
    - traitlets==5.14.2
    - transformers==4.39.3
    - tree-sitter-languages==1.10.2
    - tree-sitter==0.21.3
    - triton==2.2.0
    - typing-extensions==4.9.0
    - tzdata==2024.1
    - tzlocal==5.2
    - urllib3==2.1.0
    - validators==0.28.0
    - watchdog==4.0.0
    - wcwidth==0.2.13
    - wget==3.2
    - wheel==0.41.2
    - xxhash==3.4.1
    - yarl==1.9.4
prefix: /fruitbasket/users/dtredsox/anaconda3/envs/llm-merging
